
Algorytm tradycyjny
```{r}
classic_multiplication <- function(mtr1, mtr2) {
  # Number of operations: +-* /
  flops <- 0
  sum <- 0
  
  # The shape of the result matrix will be: <number of rows from the  first matrix> x <number of columns from the second matrix>
  result_matrix <- matrix(0, nrow = nrow(mtr1), ncol = ncol(mtr2))
  
  # Number of columns in the first matrix = number of rows in the second matrix
  # (this variable will help us with the most inner iteration)
  size <- ncol(mtr1)
  
  # Iterate over rows of the first matrix
  for (i in 1:nrow(mtr1)) {
    
    # Iterate over columns of the second matrix
    for (j in 1:ncol(mtr2)) {
      
      # "k" denotes columns in the first matrix and rows in the second matrix
      for (k in 1:size) {
        
        sum <- sum + mtr1[i, k] * mtr2[k, j]
        flops <- flops + 2
        
      }
      
      result_matrix[i, j] <- sum
      sum <- 0
      
    }
  }
  
  # Return a list containing the result matrix and the number of operations
  return(list(result_matrix, flops))
}

# Example usage with two matrices
# Macierze M1 i M2
M1 <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3)
M2 <- matrix(c(1, 2, 3, 4, 5, 6, 1, 2, 1), nrow = 3, ncol = 3)

# Display matrices
print(M1)
print(M2)


result <- classic_multiplication(M1, M2)
print(result[[1]])  # Result matrix
print(result[[2]])  # Number of operations

```



Algorytm Strassena

```{r}
strassen_multiply <- function(A, B) {
  
  n <- nrow(A)
  
  # for 2x2 matricies we use classic multiplication
  if (n <= 2) {
    return(classic_multiplication(A, B)
  }
  
  # Division into "sub" matricies
  new_size <- n %/% 2
  A11 <- A[1:new_size, 1:new_size]
  A12 <- A[1:new_size, (new_size + 1):n]
  A21 <- A[(new_size + 1):n, 1:new_size]
  A22 <- A[(new_size + 1):n, (new_size + 1):n]
  
  B11 <- B[1:new_size, 1:new_size]
  B12 <- B[1:new_size, (new_size + 1):n]
  B21 <- B[(new_size + 1):n, 1:new_size]
  B22 <- B[(new_size + 1):n, (new_size + 1):n]
  
  # Recursive multiplication
  P1 <- strassen_multiply(A11 + A22, B11 + B22)
  P2 <- strassen_multiply(A21 + A22, B11)
  P3 <- strassen_multiply(A11, B12 - B22)
  P4 <- strassen_multiply(A22, B21 - B11)
  P5 <- strassen_multiply(A11 + A12, B22)
  P6 <- strassen_multiply(A21 - A11, B11 + B12)
  P7 <- strassen_multiply(A12 - A22, B21 + B22)
  

  C11 <- P1 + P4 - P5 + P7
  C12 <- P3 + P5
  C21 <- P2 + P4
  C22 <- P1 - P2 + P3 + P6
  
  # joinung the results
  result <- matrix(0, n, n)
  result[1:new_size, 1:new_size] <- C11
  result[1:new_size, (new_size + 1):n] <- C12
  result[(new_size + 1):n, 1:new_size] <- C21
  result[(new_size + 1):n, (new_size + 1):n] <- C22
  
  return(result)
}
```


```{r}
A <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16), nrow = 4)
B <- matrix(c(17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32), nrow = 4)

result <- strassen_multiply(A, B)
print(result)

```
```{r}
classic_multiplication(A, B)
```
